services:
  - name: user-service
    type: web
    plan: free
    runtime: docker
    rootDir: backend
    branch: main
    autoDeploy: true
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tattoo-app-db
          property: connectionString
      - key: PORT
        value: 8080

databases:
  - name: tattoo-app-db
    plan: free
    region: oregon
